{% set name = "aiida-optimize" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiida-optimize-{{ version }}.tar.gz
  sha256: 8df97556c8221d4760d5b0ea4af5446a7b5c0a2138e1cc26dc1cdb2bb8177715

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.4.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - aiida-core >=2.0.0,<3.0.0
    - numpy
    - scipy
    - decorator
    - pyyaml

test:
  imports:
    - aiida_optimize
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aiida-optimize.readthedocs.io/
  summary: AiiDA Plugin for running optimization algorithms.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjsewell
